## .github/actions/setup/action.yml
#
#name: Setup
#description: Setup node and install dependencies
#
#runs:
#  using: 'composite'
#  steps:
#    - name: Setup Node.js
#      uses: actions/setup-node@v3
#      with:
#        node-version: 18
#
#    - name: Cache node modules
#      uses: actions/cache@v2
#      with:
#        path: |
#          ~/.npm
#        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#        restore-keys: |
#          ${{ runner.os }}-node-
#
#    - name: Install Dependencies
#      shell: bash
#      run: npm install
