import {defineConfig} from "orval";

export default defineConfig({
  maocars: {
    output: {
      mode: 'split',
      target: 'src/maocars-client/maocars.ts',
      schemas: 'src/maocars-client/schemas',
      client: 'react-query',
      mock: false,
      override: {
        header: () => `/* eslint-disable */ 
          /**
           * Generated by orval 🍺
           * Do not edit manually.
           * mao-cars-api
           */
        `,
        mutator: {
          path: 'src/maocars-client/fetch-instance.ts',
          name: 'customInstance',
        },
        query: {
          signal: false,
          options: {
            refetchOnMount: false,
          }
        },
        useTypeOverInterfaces: false,
      },
      tslint: false,
    },
    input: {
      target: 'src/maocars-client/spec.yaml',
    },
    hooks: {
      afterAllFilesWrite: 'npm run format',
    },
  },
})
