/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */

export type AuctionStatus = (typeof AuctionStatus)[keyof typeof AuctionStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuctionStatus = {
  live: 'live',
  ended: 'ended',
} as const;
