/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */

export type AuctionStatus = {
  for_army_forces: boolean;
  has_inspection: boolean;
  no_reserve: boolean;
  reserved: boolean;
};
