/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */

export type CarSections = {
  equipment: string;
  highlights: string;
  known_flaws: string;
  modifications?: string;
  other_items?: string;
  ownership_history: string;
  recent_service_history: string;
  videos?: string[];
};
