/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */

export type CommentType = (typeof CommentType)[keyof typeof CommentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommentType = {
  text: 'text',
  bid: 'bid',
} as const;
