/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */

export type GetAuctionsTransmission =
  (typeof GetAuctionsTransmission)[keyof typeof GetAuctionsTransmission];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAuctionsTransmission = {
  all: 'all',
  automatic: 'automatic',
  manual: 'manual',
} as const;
