/* eslint-disable */

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */
import type { GetAuctionsBodyStyle } from './getAuctionsBodyStyle';
import type { GetAuctionsSort } from './getAuctionsSort';
import type { GetAuctionsTransmission } from './getAuctionsTransmission';

export type GetAuctionsParams = {
  startYear?: string;
  endYear?: string;
  bodyStyle?: GetAuctionsBodyStyle;
  transmission?: GetAuctionsTransmission;
  sort?: GetAuctionsSort;
};
