/* eslint-disable */

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */
import type { Auction } from './auction';

export type GetAuctions200 = {
  auctions: Auction[];
  count: number;
  total: number;
};
