/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */

export type GetAuctionById200Status =
  (typeof GetAuctionById200Status)[keyof typeof GetAuctionById200Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAuctionById200Status = {
  live: 'live',
  end: 'end',
} as const;
