/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */

export type GetAuctionsParams = {
  startYear?: string;
  endYear?: string;
  bodyStyle?: string;
  transmission?: string;
  sort?: string;
};
