/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */

export type GetAuctionsBodyStyle = (typeof GetAuctionsBodyStyle)[keyof typeof GetAuctionsBodyStyle];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAuctionsBodyStyle = {
  all: 'all',
  coupe: 'coupe',
  convertible: 'convertible',
  hatchback: 'hatchback',
  sedan: 'sedan',
  SUV: 'SUV',
  truck: 'truck',
  van: 'van',
  wagon: 'wagon',
} as const;
