/* eslint-disable */

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */
import type { UserShort } from './userShort';

export type GetAuctionById200StatsCurrentBid = {
  amount: number;
  bidder: UserShort;
};
