/* eslint-disable */

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */
import type { GetAuctionById200StatsCurrentBid } from './getAuctionById200StatsCurrentBid';

export type GetAuctionById200Stats = {
  auction_end: string;
  bids: number;
  comments: number;
  current_bid: GetAuctionById200StatsCurrentBid;
  questions: number;
  watchers: number;
};
