/* eslint-disable */

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */
import type { GetCommentsByAuctionIdFilter } from './getCommentsByAuctionIdFilter';

export type GetCommentsByAuctionIdParams = {
  /**
   * Filter for comments (newest, most_upvoted, seller_comments, bid_history)
   */
  filter?: GetCommentsByAuctionIdFilter;
};
