/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */

export type GetCommentsByAuctionIdFilter =
  (typeof GetCommentsByAuctionIdFilter)[keyof typeof GetCommentsByAuctionIdFilter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetCommentsByAuctionIdFilter = {
  newest: 'newest',
  most_upvoted: 'most_upvoted',
  seller_comments: 'seller_comments',
  bid_history: 'bid_history',
} as const;
