/* eslint-disable */

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */
import type { Comment } from './comment';

export type GetCommentsByAuctionId200 = {
  comments_and_bids: Comment[];
  count: number;
};
