/* eslint-disable */

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */
import type { Car } from './car';
import type { UserProfileInfo } from './userProfileInfo';

export interface User {
  cars_auctioned: Car[];
  id: string;
  profile_info: UserProfileInfo;
}
