/* eslint-disable */

/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */
import type { Auction } from './auction';
import type { UserProfileInfo } from './userProfileInfo';

export interface User {
  cars_auctioned: Auction[];
  id: string;
  profile_info: UserProfileInfo;
}
