/* eslint-disable */
/**
 * Generated by orval 🍺
 * Do not edit manually.
 * mao-cars-api
 */

export type UserProfileInfo = {
  bio: string;
  created_at: string;
  photo?: string;
  reputation: number;
  username: string;
};
